### ISSUE TITLE
Additional questions to the Client - REQUIREMENTS PHASE

### ISSUE THREAD

**Issue by kkalista** [MWO-team2/Dziekanat#12]
Hello all,

I am about to send an email to our Client with additional questions regarding the requirements.

Please review them and add some comments/ additional questions etc.
The below is the version of questions to be used in a final email.

1. Czy potrzebujemy inne dodatkowe dane dotyczące prowadzących niż imię i nazwisko?
	Czy przypisujemy prowadzącemu np. przedmioty, które prowadzi i/lub grupy dziekanatowe, które ma pod swoją opieką?
	Czy są jeszcze inne dane, które nie zostały wspomniane a powinny być przypisane prowadzącemu?

2. Czy istnieje opcja wykreślenia studenta z listy studentów? Jeśli tak, to jakie warunki muszą być spełnione aby można było tego dokonać?

3. System ma umożliwiać generowanie poniższych raportów:
	- Lista ocen konkretnego studenta
	- Lista ocen z danego przedmiotu (według grup dziekanatowych)
	- Lista studentów warunkowych
	Czy są to oczekiwane raporty? Czy należy dodać inne, nie wspomniane wyżej raporty? Jeśli tak, to jakie?

4. Jak mają być określane ramy czasowe semestru? Czy Administator ma możliwość ręcznego ustawienia dat semestru tj. od - do?

5. Co rozumiemy przez "Zamknięcie semestru"? Czy jest to data "do", która została ustalona jako koniec semestru, czy inna data, do której np. mogą być wprowadzane oceny?

6. Jak ma wyglądać obsługa trybów?
	Czy student przechodzi na kolejny semestr w trybie NORMALNYM jeśli np. osiągnie minimalną ilość punktów ECTS do zaliczenia semestru (pyt. kto wprowadza tę wartość? Czy możemy przyjąć, ze to jest wartość stała np. 60 pkt. ECTS na semestr) PLUS zaliczy wszystkie przypisane przedmioty?
	Czy student przechodzi na kolejny semestr w trybie WARUNKOWYM jeśli osiągnie określony Procent z całości wymaganych ECTS na semestr PLUS ma tylko jeden niezaliczony przedmiot?
	Czy powyższe rozumowanie jest zgodne z oczekiwanym? Jeśli nie to proszę o sprostowanie.
        Dodatkowo, jakie warunki musi spełnić student aby mieć możliwość wzięcia urlopu lub powtarzania semestru.

**Comment by bockowsk** [comment]
ja powiem tak: ja bym tak nie przeginal. W sensie wyslalbym mu najpierw wstep, ze ten e-mail bedzie do "klienta" i do prowadzacego. Jako mail do klienta powiedzialym mu, ze takbysmy to prowadzili, ale jako tresc do prowadzacego powiedzialbym, ze za bardzo brnemy w detale i jest to dla nas bezowocne, stracimy czas i energie na dopieszczanie projektu, z ktorego i tak nic nie bedzie. Najwazniejsze : 1. wspolpracowac, 2. wykonac dobra dokumentacje, 3. zrobic funkcjonujacyt produkt, 4. uzyc nowych technologii i wiele sie nauczyc, wiec jak np. bede mial zrobic controller do obslugi logowania, to juz bym olal rejestrowanie, 10if'ow na rozne skrajne warunki i mega fajna grafike.
Taka jest moja opinia, nie wiem co reszta.

**Comment by Yankowski** [comment]
Świetna robota, naprawdę bardzo szczegółowo opisane, konkretne pytania!
Jeżeli chodzi o moje zdanie, to ja bym pominął 6 pytanie, zrobił "ręczne" zmienianie trybu studenta i jeżeli przyjdzie wymaganie od klienta aby je rozbudować to będzie trzeba więcej czasu na to poświęcić.

**Comment by marcinmicek** [comment]
Też uważam, że punkt 6 to coś na później (jak zostanie czasu i jak klient będzie bardziej wymagający :)). Ogólnie bardzo fajnie to wszystko rozpisałaś, no i zobaczymy jak się do tego ustosunkuje nasz "Klient"...

**Comment by bockowsk** [comment]
@kkalista dobra, wiekszosc sie wypowiedziala, ogolnie swietny mail, tak wiec jak mozesz prosze wyslij z zaznaczeniem, ze ten punkt 6 to jest dalszy rozwoj i nie jest priorytetowe. 
Zamykam.

**Comment by kkalista** [comment]
Ok, mail poszedl. Punkty 1-5. 6ty pominęłam, jak tak mówiliście. Według mnie Klient i Opiekun sobie zdają sprawę, że nie zrobimy całej aplikacji, ale mamy zebrać dokładne wymagania. I wtedy im powiedzieć co z tych wymagań jesteśmy w stanie pokryć w tak krótkim czasie. Bo już widzę jak Klient się nas dopytuje na zaliczeniu: "A dlaczego zrobiliście to na niebiesko, jak ja chciałem, żeby było różowe?" To taki bardzo ogólny przykład ale wiecie o co mi chodzi? Oni to mają głównie na uwadze. 

Jak tylko dostanę odpowiedź to Wam wyślę.

**Comment by kkalista** [comment]
Witam,

przed Świętami byłem służbowo w rozjazdach, dopiero teraz
nadrabiam zaległości. Odpowiedzi poniżej.

Pozdrawiam,

MKD

On 2018-03-24 12:11, katarzynakalista@wp.pl wrote:
Szanowny Panie Kisiel-Dorohinicki,

Jestem przedstawicielem Grupy 2, pracującej nad projektem Dziekanat.

Piszę do Pana w celu wyjaśnienia kilku kwestii związanych z wymaganiami
projektowymi.
Czy mogłabym prosić Pana o zapoznanie się z poniższymi pytaniami i
udzielenie odpowiedzi?

Pytania:
1. Informacje o prowadzącym
Czy potrzebne są inne, dodatkowe dane dotyczące prowadzących niż imię i
nazwisko?
adres, PESEL

Czy przypisujemy prowadzącemu np. przedmioty, które prowadzi i/lub grupy
dziekanatowe, które ma pod swoją opieką?
każdy przedmiot ma osobę odpowiedzialną, poza tym tylko to
co wynika z grafiku prowadzenia zajęć

Czy są jeszcze inne dane, które nie zostały wspomniane a powinny być
przypisane prowadzącemu?
nie

2. Czy istnieje opcja wykreślenia studenta z listy studentów? Jeśli tak,
to jakie warunki muszą być spełnione aby można było tego dokonać?
skreślenie następuje w wyniku rezygnacji albo niespełnienia
warunków zaliczenia semestru

3. System ma umożliwiać generowanie poniższych raportów:
Lista ocen konkretnego studenta
Lista ocen z danego przedmiotu (według grup dziekanatowych)
to raczej wszystko

Lista studentów warunkowych
to jest dla mnie raczej efekt filtrowania listy studentów
(nie ma konieczności generowania dokumentu)

Czy są to oczekiwane raporty? Czy należy dodać inne, nie wspomniane
wyżej raporty? Jeśli tak, to jakie?

4. Jak mają być określane ramy czasowe semestru? Czy Administator ma
możliwość ręcznego ustawienia dat semestru tj. od - do?
tak

5. Co rozumiemy przez "Zamknięcie semestru"? Czy jest to data "do",
która została ustalona jako koniec semestru, czy inna data, do której
np. mogą być wprowadzane oceny przez prowadzących?
mamy 3 daty kończące semestr: koniec zajęć, koniec wprowadzania
ocen i zamknięcie systemu (wydaje mi się, że nazwy są jasne?)

Proszę serdecznie o odpowiedź.

Z poważaniem,
Katarzyna Kalista




--
Marek KISIEL-DOROHINICKI
Head of Computer Science Department
AGH University of Science and Technology, Krakow, Poland
http://galaxy.agh.edu.pl/~doroh
